ip = '127.0.0.1'
port = 8000
createdirs = false
altmainsite = []
file_tmp_path = './temp'
file_path = './files'

[orgauth_config]
mainsite = 'http://localhost:8000'
appname = 'zknotes'
emaildomain = 'zknotes.com'
db = './zknotes.db'
admin_email = 'admin@admin.admin'
regen_login_tokens = true
email_token_expiration_ms = 86400000
reset_token_expiration_ms = 86400000
invite_token_expiration_ms = 604800000
open_registration = false
send_emails = false
non_admin_invite = true
remote_registration = true
